name: My First parallel action
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build Docker1
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker1
      run: |
        docker build -t test .
  build-2:
    name: Build Docker2
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker2
      run: |
        docker build -t test .
  build-3:
    name: Build Docker3
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker3
      run: |
        docker build -t test .
  build-4:
    name: Build Docker4
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker4
      run: |
        docker build -t test .
  build-5:
    name: Build Docker5
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker5
      run: |
        docker build -t test .
