name: Kubernetes Arc Job

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: ghr-runner-set
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          apt-get update && apt-get install -y curl

      - name: Run Sample Command
        run: echo "Hello from Kubernetes Arc!"
