name: Kubernetes Arc with Docker-in-Docker

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: ghr-runner-set
    container:
      image: docker:24-dind  # Using Docker-in-Docker (DinD) image
      options: --privileged  # Required for DinD

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start Docker Daemon
        run: |
          dockerd-entrypoint.sh --debug &  # Start Docker in background
          sleep 5  # Give it some time to initialize

      - name: Verify Docker
        run: docker version

      - name: Build Docker Image
        run: |
          docker build -t my-sample-app .
      
      - name: Run Container
        run: |
          docker run --rm my-sample-app

