name: Test ARC Action
on: 
  workflow_dispatch
jobs:
  fExplore-Githup-Actions:
     runs-on: git-first-action
     container: debian:stable-slim
     steps:
     - run: echo "Hello Manyejoh, fun using scaleset"
     
