name: Second Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Print salut
        run: echo "Hello Manyejoh!"
      - name: Print good day
        run: echo "Done - bye Anyangwa!"
      - name: Print say Hello sunshine
        run: echo "How is actions 5!"
  Second-job:
    runs-on: self-hosted
    steps:
      - name: Print salut
        run: echo "Hello Manyejoh!"
      - name: Print good day
        run: echo "Done - bye Anyangwa!"
      - name: Print say Hello sunshine
        run: echo "How is actions 5!"
  Third-job:
    runs-on: self-hosted
    steps:
       - name: Print salut
         run: echo "Hello Manyejoh!"
       - name: Print good day
         run: echo "Done - bye Anyangwa!"
       - name: Print say Hello sunshine
         run: echo "How is actions 5!"
  build:
    name: Build Docker
    runs-on: self-hosted
    steps:
       - name: Checkout
         uses: actions/checkout@v2

       - name: Build docker
         run: |
           docker build -t test .
